name: CI

on:
  push:
    branches:
      - can-revert
  pull_request:

jobs:
  macOS:
    runs-on: macos-12
    env:
      HOME: /Users/runner
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3

      - name: Install packages
        run: |
          brew update
          brew install pkg-config ninja meson

      - name: Install dependencies
        env:
          ARCHIVE_NAME: deps2_osx_native_dyn_libkiwix.tar.xz
        run: |
          wget -O- https://tmp.kiwix.org/ci/${{env.ARCHIVE_NAME}} | tar -xJ -C ${{env.HOME}}

      - name: Compile source code
        env:
          PKG_CONFIG_PATH: ${{env.HOME}}/BUILD_native_dyn/INSTALL/lib/pkgconfig
          CPPFLAGS: -I${{env.HOME}}/BUILD_native_dyn/INSTALL/include
        run: |
          meson . build --default-library=shared -Db_coverage=true
          ninja -C build

      - name: Test libkiwix
        env:
          SKIP_BIG_MEMORY_TEST: 1
          LD_LIBRARY_PATH: ${{env.HOME}}/BUILD_native_dyn/INSTALL/lib:${{env.HOME}}/BUILD_native_dyn/INSTALL/lib64
        run: meson test -C build --verbose
